### ISSUE TITLE
tpu_estimator.py won't work in tensorflow 1.14

### ISSUE THREAD

**Issue by LiweiPeng** [zihangdai/xlnet#188]
The XLNET's tpu_estimator.py code won't work in tensorflow 1.14. What's XLNET's plan to support newer tensorflow like 1.14 and beyond?

The XLNET's tpu_esimator.py is based on tf 1.13.1. However, the tpu_estimator design in tensorflow-estimator 1.14 (which is used by tf 1.14),  has significant change from previous versions. This caused problem when running tensorflow 1.14 on XLNET.

For example, one error I got is
tpu_estimator.py, line 2224, in __init__
    self._ctx = tpu_context._get_tpu_context(
AttributeError: 'module' object has no attribute '_get_tpu_context'
